### PR TITLE
Add Chinese support to README_CN.md

### PR DESCRIPTION
**Pull request by danyi**
I translated your README into Chinese

Many Chinese players like your contribution

If you don't like it

Please don't adopt my plan

### CODE REVIEW

**Comment by cherinyy** [comment]
https://github.com/theVakhovskeIsTaken/holoiso/blob/e0fbdf0f41cb7af64be0f8533b01d2ada531d9cd/README_CN.md?plain=1#L10

It is not recommended to describe `SteamOS 3 (Holo) archiso configuration.` as `SteamOS 3 (Holo) is built on Arch Linux.`, and should be `Arch Linux` instead of `ArchLinux`.

This project is the [archiso](https://wiki.archlinux.org/title/archiso)  configuration, not the official build of Valve's `SteamOS 3 (Holo)`.

When you encounter something you do not understand, you should ask questions rather than translating directly to your own meaning.

**Comment by cherinyy** [comment]
And I suggest changing the file name to `README.zh_CN.md`.

**Comment by danyi** [comment]
> https://github.com/theVakhovskeIsTaken/holoiso/blob/e0fbdf0f41cb7af64be0f8533b01d2ada531d9cd/README_CN.md?plain=1#L10
> 
> It is not recommended to describe `SteamOS 3 (Holo) archiso configuration.` as `SteamOS 3 (Holo) is built on Arch Linux.`, and should be `Arch Linux` instead of `ArchLinux`.
> 
> This project is the [archiso](https://wiki.archlinux.org/title/archiso) configuration, not the official build of Valve's `SteamOS 3 (Holo)`.
> 
> When you encounter something you do not understand, you should ask questions rather than translating directly to your own meaning.

Yes, you are right, then how do you think it should be translated?

**Comment by cherinyy** [comment]
> how do you think it should be translated?

just like the original

> SteamOS 3 (Holo) archiso 配置。

**Comment by theVakhovskeIsTaken** [comment]
I'll be pushing it later! Can you please update it with current information?

**Comment by danyi** [comment]
Ok, I will update in the near future

**Comment by danyi** [comment]
I updated it

**Pull request merged**
